# Generated by Django 5.0.3 on 2024-03-17 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=10000)),
            ],
            options={
                "verbose_name": "material",
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=10000)),
                ("product_code", models.TextField(null=True)),
            ],
            options={
                "verbose_name": "product",
            },
        ),
        migrations.CreateModel(
            name="WareHouses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remainder", models.FloatField()),
                ("price", models.FloatField()),
                (
                    "material_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.materials",
                    ),
                ),
            ],
            options={
                "verbose_name": "ware_house",
            },
        ),
        migrations.CreateModel(
            name="Product_Materials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.FloatField()),
                (
                    "material_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.materials",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.products",
                    ),
                ),
                (
                    "warehouse_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.warehouses",
                    ),
                ),
            ],
            options={
                "verbose_name": "product_material",
            },
        ),
    ]
